"""GraphBackend protocol declaring the common query interface.

Both static GraphQuery (AST/Grep) and LSPGraphQuery satisfy this protocol.
"""

from typing import Protocol, List, Dict, Any, Optional, runtime_checkable

@runtime_checkable
class GraphBackend(Protocol):
    def callers_of(self, symbol_or_node_id: str, max_depth: int = 5) -> List[Dict[str, Any]]: ...
    def callees_of(self, symbol_or_node_id: str, max_depth: int = 5) -> List[Dict[str, Any]]: ...
    def reachable_from(self, input_file: str, input_line: int, sink_symbol: str) -> bool: ...
    def blast_radius(self, symbol_or_node_id: str, max_depth: int = 3) -> Dict[str, Any]: ...
    def status(self) -> Dict[str, Any]: ...
